title: Joshua Marple
description: A personal blog about software development
author: Joshua Marple

theme_config:
  back_home_text: "‚Üê back"

# Build settings
markdown: kramdown
kramdown:
  math_engine: null
sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag

# Permalink structure
permalink: /:year/:month/:day/:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - Justfile
  - README.md
