title: Joshua Marple
description: A personal blog about software development
author: Joshua Marple

# Build settings
markdown: kramdown
remote_theme: riggraz/no-style-please

plugins:
  - jekyll-remote-theme

# Permalink structure
permalink: /:year/:month/:day/:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - Justfile
  - README.md
